name: ggd_ggdmart
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  velocity_x: ^4.1.1
  get: ^4.6.5
  firebase_core: ^2.24.2
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.14.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter_native_splash:
  color: "#E62E04"
  image: assets/applogo.png
  android_12:
    icon_background_color: "#E62E04"
    image: assets/applogo.png



flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - lib/services/category_model.json

  fonts:
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf

    - family: sans_semibold
      fonts:
        - asset: assets/fonts/sans_semibold.ttf

    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf

